version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run: dotnet build --runtime linux-x64 --configuration Release --framework netcoreapp3.1
    #  - store_artifacts:
    #      path: C:/Users/circleci/project/bin/Release/netcoreapp3.1/linux-x64/

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST:/var/www/vhosts/prilogy.ru/test -p 22


workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master