version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    working_directory: ~/app-build
    steps:
      - checkout
      - run: dotnet build --runtime linux-x64 --configuration Release --framework netcoreapp3.1

  deploy:
    machine:
      enabled: true
    working_directory: ~/app-build
    steps:
      - run:
          name: Deploy over SSH
          command: |
            ls ~/app-build
            scp -r ~/app-build/bin/Release/netcoreapp3.1/linux-x64 $SSH_USER@$SSH_HOST:$SSH_FOLDER
            ssh $SSH_USER@$SSH_HOST "sudo supervisorctl restart ExtremeInsiders"


workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master